### ISSUE TITLE
Discussion: Streamlit Privacy and Audio Recording Questions

### ISSUE THREAD

**Issue by lunar-studio** [BoltzmannEntropy/xtts2-ui#11]
Not an issue, but two questions as I'm unfamiliar with Streamlit:

1. What's the default privacy settings for streamlit? I know with Gradio default settings, if you set it to share it's public and others can use your system unless you username and pass protect it. Is it the same for Streamlit by default?
2. How easy, difficult, or impossible is it to incorporate this Audio Recording Streamlit into the existing interface/code? I would love to figure this out:
https://github.com/Joooohan/audio-recorder-streamlit

**Comment by lunar-studio** [comment]
Here's another Audio Recorder which might be a better fit:
https://github.com/stefanrmmr/streamlit-audio-recorder

**Comment by BoltzmannEntropy** [comment]
I will have a look, thanks.

**Comment by BoltzmannEntropy** [comment]
As the current recording is working well, I am closing this for now.
