### ISSUE TITLE
Feature: Run on local with an option listen=True

### ISSUE THREAD

**Issue by Coriolan-Bataille** [BoltzmannEntropy/xtts2-ui#20]
At the moment, xtts2-ui can be launch on http://127.0.0.1:7865 or with a public url via the option share=True.
Port forwarding create lot of issues.
Is there any way to configure to be accessible on the local network? or add the option listen=True.

Thx for sharing with the community your amazing work,
best regards,
Cory

**Comment by BoltzmannEntropy** [comment]
If I understand you correctly, you can change the bind address to 0.0.0.0 and then use your local IP to access it over from another computer on the same network.
