### ISSUE TITLE
ConnectionError: Unable to download models

### ISSUE THREAD

**Issue by aryiby** [BoltzmannEntropy/xtts2-ui#32]
### Problem
It looks like I'm unable to download the base model files because I'm getting a ConnectionError:
```
HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443):
Max retries exceeded with url:
  /hf-coqui/XTTS-v2/main/model.pth
  (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x78d0bfff4c10>:
    Failed to resolve 'coqui.gateway.scarf.sh' ([Errno -3] Temporary failure in name resolution)"))
```

### What I've tried so far
Some people have suggested that I need to set the environment variable, `TRAINER_TELEMETRY` to `0`[^1]; however, that hasn't made a difference. I am still seeing the same error.

### Next steps

I'm not sure what next steps to take.
* Can I manually download the base model files and put them where they're expected?
* Maybe I can clone xtts2 and try running it manually first?

[^1]: [TTS discussion](https://github.com/coqui-ai/TTS/discussions/2586)

**Comment by BoltzmannEntropy** [comment]
I am able to reproduce the error. It seems intentional on behalf of Coq, the model creator, and I have no control over this. There are some alternatives now, take a look at: 
https://github.com/jianchang512/ChatTTS-ui
