### ISSUE TITLE
Explanation copy Pranav Banuru 

### ISSUE THREAD

**Issue by kalle07** [BoltzmannEntropy/xtts2-ui#37]
why no explanation why is this a copy of 
https://github.com/pbanuru/xtts2-ui

Pranav Banuru is also in this one ?!?

**Comment by BoltzmannEntropy** [comment]
What are you asking exactly? There are 40 forks of our project, one of them is https://github.com/pbanuru/xtts2-ui as clearly indicated on his repo.

**Comment by kalle07** [comment]
i see sry on forks ...
they all the same ???  is that only to publish ?  ^^

**Comment by BoltzmannEntropy** [comment]
I have no control over forks.
