### ISSUE TITLE
Bug/Error: Max retries exceeded with url: /hf-coqui/XTTS-v2/main/model.pth

### ISSUE THREAD

**Issue by lunar-studio** [BoltzmannEntropy/xtts2-ui#6]
Initiating app.py after accepting the agreement then hitting this roadblock:

HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /hf-coqui/XTTS-v2/main/model.pth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000192A0C3E3E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by lunar-studio** [comment]
Wow. It looks like they took access down. Appears the XTTS Model is still up on HF.. Do you have any suggestions for alternatives or workarounds?
https://news.ycombinator.com/item?id=38437743

**Comment by BoltzmannEntropy** [comment]
If you download teh models from HF and place them under:
`/home/${USER}/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2` it should work, though I did not test this.

**Comment by lunar-studio** [comment]
Awesome work by the way which is why I would love to see this continue on.

That being said, I’m on Windows and had already tried to put the models under a local directory. The folder tts_models… doesn’t exist but perhaps I need to create it. 

I’m wondering if I could somehow change the URL listed under manage.py (somewhere I think it was in site-packages) to the HF URL, if this would work instead. But truthfully, it would be even better if we could specify in the UI where a model is locally installed, thereby bypassing any future issues with URLs disappearing.

**Comment by BoltzmannEntropy** [comment]
But we did- the readme clearly indicate where the models are located on Windows:
`C:\Users\ YOUR-USER-ACCOUNT \AppData\Local\tts\tts_models--multilingual--multi-dataset--xtts_v2`

**Comment by lunar-studio** [comment]
I just double-checked and there's no folder created by that name. However I had stuck those models in:
`C:\Users\ YOUR-USER-ACCOUNT \AppData\Local\tts\`

I did manage to circumvent that error now by manually creating that missing folder and dropping the models into there.

Perhaps it's not being created because the app hits the 404 first then spits out an error? It could on the other hand be a strange win 11 permissions error. However I would think that the directory would be created first and THEN the files would be downloaded to that directory.
