### ISSUE TITLE
CUDA 12.3 and Pytorch Question

### ISSUE THREAD

**Issue by lunar-studio** [BoltzmannEntropy/xtts2-ui#7]
This may be more appropriate for the PyTorch forums but are you aware of any easy way to get this to work with 12.3 or do I have to manually build it? It looks like PyTorch only supports only up to CUDA 12.1.

**Comment by DustanGiles** [comment]
[https://discuss.pytorch.org/t/question-i-have-a-question-about-installing-pytorch/191829](https://discuss.pytorch.org/t/question-i-have-a-question-about-installing-pytorch/191829)

**Comment by BoltzmannEntropy** [comment]
I did not test it with CUDA 12.3 and I only have OSX.
