### ISSUE TITLE
Share or Listen Parameters?

### ISSUE THREAD

**Issue by lunar-studio** [BoltzmannEntropy/xtts2-ui#8]
Last question: I'm familiar with SD where I'd  modify a launch.bat, but is there anywhere I can modify this (either share or listen) so I can work over my network?

**Comment by lunar-studio** [comment]
To answer my own question (in case it helps anyone else), you would replace the following at the bottom of app.py:
    app.launch()

with (for "listening" or rather local network sharing):
`    app.launch(server_name="0.0.0.0", server_port=7860)
`
or for a 72 hour Gradio share (public/Internet facing although I recommend a username and password - obviously change it from the example below):
`    app.launch(auth=("admin", "pass1234"), share=True)`

**Comment by BoltzmannEntropy** [comment]
Thanks!
